eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: wx-resource-engine
    devtools:
        restart:
            #热部署生效
          enabled: true
#            #设置重启的目录
#            #additional-paths: src/main/java
#            #classpath目录下的WEB-INF文件夹内容修改不重启
#          exclude: WEB-INF/**
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties/